name: PHP Syntax Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  php-lint:
    name: Check PHP Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: none

      - name: Print base branch
        run: echo "Base branch is:${{ github.base_ref }}"    
          
      - name: Get changed files
        id: changed-files
        run: |
          # Get list of changed PHP files
          git fetch origin ${{ github.base_ref }}
          echo "files=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }} | grep '\.php$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: PHP Syntax Check
        run: |
          # Exit gracefully if no PHP files were changed
          changed_files="${{ steps.changed-files.outputs.files }}"
          if [ -z "$changed_files" ]; then
            echo "ℹ️ No PHP files were changed in this PR"
            exit 0
          fi

          echo "🔍 Changed PHP files:"
          echo "$changed_files"

          echo "🔍 Checking syntax for changed PHP files..."
          
          # Initialize error flag
          error_found=0
          
          # Check each changed file
          for file in $changed_files; do
            echo "Checking (pre-existence): $file"
            if [ -f "$file" ]; then
              echo "Checking: $file"
              if ! php -l "$file"; then
                error_found=1
              fi
            fi
          done
          
          # Exit with error if any syntax issues were found
          if [ $error_found -eq 1 ]; then
            echo "❌ Syntax errors were found"
            exit 1
          else
            echo "✅ All PHP files passed syntax check"
          fi
